scp -P 10022 jinoue@yurai.aori.u-tokyo.ac.jp:/var/www/html/oeDNAmap/ASVtables/Closek19.xlsx . 
scp -P 10022 jinoue@yurai.aori.u-tokyo.ac.jp:/var/www/html/oeDNAmap/ASVtables/OTU_Closek19_Ex.xlsx . 
scp -P 10022 jinoue@yurai.aori.u-tokyo.ac.jp:/var/www/html/oeDNAmap/ASVtables/ASV_KH20-9_KH22-5_Ex.xlsx . 
scp -P 10022 jinoue@yurai.aori.u-tokyo.ac.jp:/var/www/html/oeDNAmap/ASVtables/ASV_KH22-5_Ex.xlsx . 
scp -P 10022 jinoue@yurai.aori.u-tokyo.ac.jp:/var/www/html/oeDNAmap/ASVtables/ASV_KH20-9_Ex.xlsx . 
scp -P 10022 jinoue@yurai.aori.u-tokyo.ac.jp:/var/www/html/oeDNAmap/ASVtables/KH20-9AB_qiime2.xlsx . 
scp -P 10022 jinoue@yurai.aori.u-tokyo.ac.jp:/var/www/html/oeDNAmap/ASVtables/Wu24v4.xlsx . 
scp -P 10022 jinoue@yurai.aori.u-tokyo.ac.jp:/var/www/html/oeDNAmap/ASVtables/KH22-5.xlsx . 
scp -P 10022 jinoue@yurai.aori.u-tokyo.ac.jp:/var/www/html/oeDNAmap/ASVtables/Nishitsuji23.xlsx . 
scp -P 10022 jinoue@yurai.aori.u-tokyo.ac.jp:/var/www/html/oeDNAmap/ASVtables/Shinzato21.xlsx . 
scp -P 10022 jinoue@yurai.aori.u-tokyo.ac.jp:/var/www/html/oeDNAmap/ASVtables/Oka20.xlsx . 
scp -P 10022 jinoue@yurai.aori.u-tokyo.ac.jp:/var/www/html/oeDNAmap/ASVtables/Kim22.xlsx . 
scp -P 10022 jinoue@yurai.aori.u-tokyo.ac.jp:/var/www/html/oeDNAmap/ASVtables/Kawakami23.xlsx . 
scp -P 10022 jinoue@yurai.aori.u-tokyo.ac.jp:/var/www/html/oeDNAmap/ASVtables/Dukan24.xlsx . 
scp -P 10022 jinoue@yurai.aori.u-tokyo.ac.jp:/var/www/html/oeDNAmap/ASVtables/Lafferty20.xlsx . 
scp -P 10022 jinoue@yurai.aori.u-tokyo.ac.jp:/var/www/html/oeDNAmap/ASVtables/Bessey20.xlsx . 
scp -P 10022 jinoue@yurai.aori.u-tokyo.ac.jp:/var/www/html/oeDNAmap/ASVtables/Miya22.xlsx . 
scp -P 10022 jinoue@yurai.aori.u-tokyo.ac.jp:/var/www/html/oeDNAmap/ASVtables/species_TEST.csv . 
scp -P 10022 jinoue@yurai.aori.u-tokyo.ac.jp:/var/www/html/oeDNAmap/ASVtables/List_Miya15Kuroshio.txt . 
scp -P 10022 jinoue@yurai.aori.u-tokyo.ac.jp:/var/www/html/oeDNAmap/ASVtables/list_speciesName_pulldown.txt . 
